#!/usr/bin/env python3
"""
bin2c.py — convert a binary file to a C array literal.

Usage:  python3 tools/bin2c.py INPUT OUTPUT_VAR OUTPUT_C [--max-per-line N]

Generates:
    unsigned char <OUTPUT_VAR>[] = { 0xNN, 0xNN, ... };
    unsigned int  <OUTPUT_VAR>_len = NNNN;

Used to embed the builtin_stub.cdl ELF shared object into the kernel
so app_bootstrap_init() can write it into every bundle's Contents/MacOS/.
"""
import sys

def main():
    if len(sys.argv) < 4:
        sys.stderr.write("usage: bin2c.py INPUT OUTPUT_VAR OUTPUT_C [--max-per-line N]\n")
        sys.exit(2)

    inp   = sys.argv[1]
    var   = sys.argv[2]
    outp  = sys.argv[3]
    per_line = 16
    if "--max-per-line" in sys.argv:
        i = sys.argv.index("--max-per-line")
        per_line = int(sys.argv[i + 1])

    with open(inp, "rb") as f:
        data = f.read()

    with open(outp, "w") as f:
        f.write("/* Auto-generated by tools/bin2c.py — do not edit. */\n")
        f.write("/* Source: {} */\n".format(inp))
        f.write("/* Size:   {} bytes */\n\n".format(len(data)))
        f.write("unsigned char {}[] = {{\n".format(var))
        for i in range(0, len(data), per_line):
            chunk = data[i:i + per_line]
            f.write("    " + ", ".join("0x{:02x}".format(b) for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("unsigned int {}_len = {};\n".format(var, len(data)))

    sys.stderr.write("bin2c: wrote {} bytes to {} as {}\n".format(len(data), outp, var))

if __name__ == "__main__":
    main()
